FROM python:3.8-slim-buster

RUN apt-get update -y && apt-get install -y openjdk-11-jre
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY predict.py /app/

ENTRYPOINT ["python", "/app/predict.py"]